<a href="https://colab.research.google.com/github/janithpiyumal1/ML-TensorFlow/blob/main/00_TF_Fundermentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Tenser

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [ ]:
#create tensor with tf.constent
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dementions of a tensor
scalar.ndim

0

In [ ]:
#creat a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the number of dementions of the vector
vector.ndim

1

In [ ]:
#create a metrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>